### ISSUE TITLE
Undefined Var

### ISSUE THREAD

**Issue by manishkakwani** [udacity/CarND-LaneLines-P1#17]
In P1.ipynb, there are two places where you write: "plt.imshow(gray, cmap='gray')," what is gray (the variable, not the string)? Isn't that just an undefined variable? Did you mean to write "plt.imshow(image, cmap='gray')" in the first instance and "plt.imshow(img, cmap='gray')" in the second?

**Comment by ryan-keenan** [comment]
These comments are just to guide you toward using the gray colormap, `cmap="gray"`, when displaying a single color channel image.  The variable name `gray` is used assuming you might call the `grayscale()` function like: `gray = grayscale(image)`.   Before these comments were added people were trying to use `plt.imshow(gray)` for single color channel images and getting strange results.

**Comment by manishkakwani** [comment]
Hi Ryan,

Thanks, that's helpful. Would it be possible to update the README to specify that gray is var representing the result of calling the grayscale transform?

**Comment by ryan-keenan** [comment]
Hey, sure, so what I've done to be a bit more explicit is to add a few words to the comment strings where those suggestions are made.  I feel like in the readme they might get missed.  Thanks for helping improve the project!
