### ISSUE TITLE
openCV with GPU

### ISSUE THREAD

**Issue by shivajid** [udacity/CarND-LaneLines-P1#18]
I was looking to use OpenCV with Cuda8. I have Cuda8, but have not been successful with getting openCV working with it. Is there any guidelines for that?

**Comment by nachomartinr** [comment]
You have to install Cuda 8 first (which I assume you have) and compile OpenCV with at least these flags
-D WITH_CUDA=ON
-D ENABLE_FAST_MATH=
-D CUDA_FAST_MATH=1
-D WITH_CUBLAS=1

After you run cmake, you should get in the ouput that NVIDIA CUDA is enabled.

**Comment by shivajid** [comment]
Thanks nachomartinr. I tried the above steps and had some issues with OpenCV, thus raised the issue. I was wondering if you have version that you have have tried out.

**Comment by nachomartinr** [comment]
I have a GPU enabled OpenCV 3.1 installed in my computer, but compiled from sources. I had problems compiling it, but they weren't related to CUDA, but to the GCC version (OpenCV does not support GCC 6 yet). I don't know of any binary release with enabled GPU acceleration.

**Comment by baumanab** [comment]
Closed as out of scope for this repository.
