### ISSUE TITLE
Reflections Section Removed

### ISSUE THREAD

**Issue by WittmannF** [udacity/CarND-LaneLines-P1#23]
Hello, I am a code reviewer, and I would like to make sure that the removal of the Reflection section was intentional (as shown in [this commit](https://github.com/udacity/CarND-LaneLines-P1/commit/3ffa4cbeafadfd722d508bc63089ac4066b3aca3#diff-2ee7b7000ace231ad446c5d4f145c736)).

Maybe the reviewers should be warned about this update. The section is still shown as a requirement in the Reviewer Dashboard,

**Comment by mvirgo** [comment]
Thanks for noticing - we created a separate write-up template in that commit for students to use for writing their reflections.
