### ISSUE TITLE
Issue with conda install -c menpo opencv3=3.1.0

### ISSUE THREAD

**Issue by mwhayford** [udacity/CarND-LaneLines-P1#24]
With Windows 7 , after the condo install -c menpo opencv3=3.1.0 step, 
I get UnsatisfiableError: The following specifications were found to be in conflict:
 - opencv3 3.1.0* -> python 2.7*
 - python 3.6*

conda info opencv3=3.1.0 returns 

NoPackagesFoundError: Package missing in current win-64 channels:
 - opencv3 3.1.0*

Using anaconda search -t conda opencv3, the menpo/opencv3 version 3.2.0 should have a win-64 version available. but changing the top statement to use opencv3=3.2.0 but that doesnt seem to work either. Does anyone have some insight on how to solve this issue I'm having with the included instructions?

**Comment by marbeh25** [comment]
Check the forum thread:
https://discussions.udacity.com/t/unable-to-setup-opencv-on-windows/217368/5

**Comment by asimay** [comment]
the same error:
![123](https://cloud.githubusercontent.com/assets/8703449/23340351/9aa847da-fc6f-11e6-9a16-b3d3b46d3413.PNG)

and I cannot access the above forum link....
I tried many mirror, is hard to setup opencv lib....

**Comment by asimay** [comment]
wait for new miror to setup the opencv, i almost tried every mirror by `"anaconda search -t conda opencv"` , all is failed...

**Comment by qiuyi911** [comment]
@asimay , I had the same issues as you did. but I got successful installation using channel https://anaconda.org/conda-forge/opencv.
OR,  use ' conda install -c conda-forge opencv=3.2.0 ' command;
my conda version is 4.2.13.

**Comment by Frame02** [comment]
Thanks for pointing out the right channel 'conda-forge'. I have been searching for this as the [official Anaconda site ](https://anaconda.org/menpo/opencv3)points to a channel 'menpo' where the package is missing!

**Comment by psyclopz** [comment]
Thank you. conda forge worked!

**Comment by acruis** [comment]
Using `conda-forge` works for me too. Thanks!

**Comment by mvirgo** [comment]
Looks like this was solved with conda-forge above; closing.

**Comment by analyticfocus** [comment]
Opencv3 from conda-forge works like charm. Thanks!
