### ISSUE TITLE
ctrl+d , in windows, cannot exit.

### ISSUE THREAD

**Issue by asimay** [udacity/CarND-LaneLines-P1#32]
in README.md:
exit python:
> SyntaxError: invalid syntax
> >>> exit
> Use exit() or Ctrl-Z plus Return to exit
> >>> ^Z

right exit method is:   `Use exit() or Ctrl-Z plus Return to exit`

**Comment by mvirgo** [comment]
Fixed in commit 41bc314294e76d4201c2101ab3de5ca808b99b71, thank you!
