### ISSUE TITLE
Project Structure Is Inconsistent

### ISSUE THREAD

**Issue by dmlicht** [udacity/CarND-LaneLines-P1#33]
There are several inconsistencies that make this project feel a bit messy:
1. The examples folder only contains one of the five examples files
2. There is a sub directory for test images, but not one for test videos. Test videos are all kept in the root directory for some reason?
3. The project is requesting students write images back into the test image source directory, instead of a destination directory. This will give students the extra task of keeping track of which images are which if they run their pipeline on images more than once (which it seems like they should).

I would be happy to clean this up in a PR (including update the ipython notebook) if you guys are comfortable with it.

**Comment by ryan-keenan** [comment]
Thanks for the feedback David!  That would be great if you want to go ahead and clean it up to your liking and submit a PR :)

**Comment by dmlicht** [comment]
Thanks @ryan-keenan, I submitted a [PR](https://github.com/udacity/CarND-LaneLines-P1/pull/34)
