### ISSUE TITLE
The project doesn't have a license

### ISSUE THREAD

**Issue by BrandonHe** [udacity/CarND-LaneLines-P1#62]
Hi @ryan-keenan, @andrewpaster,
Notice that our project doesn't have license, that's a little unprofessional for a open source project, especially there has much extends adoption and development in an online education project. "No license terms" means users don't know it can be used freely. Another reference is [Can I call my program "Open Source" even if I don't use an approved license?](https://opensource.org/faq#avoid-unapproved-licenses).

So here I suggest the project add [license](https://opensource.org/licenses), recommend we choose one of the below license, firstly because they're all Permissive Licenses, but they have different redistribution disclaimer:
- [MIT](https://opensource.org/licenses/MIT)
- [Apache-2.0](https://opensource.org/licenses/Apache-2.0)
- [BSD-3-Clause](https://opensource.org/licenses/BSD-3-Clause)

Regards,
Brandon

**Comment by mvirgo** [comment]
Added!
