### ISSUE TITLE
No filename as test.ipynb

### ISSUE THREAD

**Issue by nsb007** [udacity/CarND-LaneLines-P1#66]
The project description on udacity says to open test.ipynb but it is not present in this repository. Do we need to work with P1.ipynb?

**Comment by mvirgo** [comment]
The `test.ipynb` file is in reference to the [Starter Kit Test repo](https://github.com/udacity/CarND-Term1-Starter-Kit-Test), not this one - note the instructions above this in the classroom that refer to cloning that repo.
