### ISSUE TITLE
Simplifying calling Docker on this project and also getting upstream fixes

### ISSUE THREAD

**Issue by richtong** [udacity/CarND-LaneLines-P1#72]
The way that you have laid this out is great and it is easy to get the docker container running, but there
are two improvements that would make things easier:

1. run.sh. Having a simple script which will allow calling that very long docker string in this directory. And at least on MacOS making sure that Docker for Mac is started
2. upstream.sh. Having a simple way to make sure that when you fork this repo, you are getting the upstream changes that Udacity is making.

I created a fork with these two simple shell scripts, is this interesting for you guys. I can issue a PR if you like.

**Comment by mvirgo** [comment]
Hi there! Thank you for the suggestion. If you want to issue a PR for this update, I will check it out.

**Comment by richtong** [comment]
Ok will do. :-)

Thanks,
Rich

—-
We need to make Windows work better. So I rewrote a section this weekend and it is 0.5% faster. That’s the way it is going to go. Every week we make it a little better. Dave Cutler, Windows NT Staff Meeting, Sept 1993. 

Sent from my iPhone X
+1-206-963-9029 | https://tongfamily.com | @richtong | https://fb.me/richtong1 |

**Comment by mvirgo** [comment]
Closing the "issue", but feel free to shoot over the PR if you are still interested.

**Comment by richtong** [comment]
Will do. Owe it to u. 

Thanks,
Rich

—-
We need to make Windows work better. So I rewrote a section this weekend and it is 0.5% faster. That’s the way it is going to go. Every week we make it a little better. Dave Cutler, Windows NT Staff Meeting, Sept 1993. 

Sent from my iPhone X
+1-206-963-9029 | https://tongfamily.com | @richtong | https://fb.me/richtong1 |
